### ISSUE TITLE
[BUG] DCO check does not check that a valid e-mail is used

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#100]
<img width="633" alt="Screen Shot 2021-07-26 at 9 24 41 AM" src="https://user-images.githubusercontent.com/542335/126996294-d0846b8c-d548-4fb3-b86a-8fd43026eb7b.png">

<img width="745" alt="Screen Shot 2021-07-26 at 9 24 33 AM" src="https://user-images.githubusercontent.com/542335/126996314-ed6f58f4-749c-4c5b-81c3-2a33636df1d1.png">

Looking at https://github.com/opensearch-project/OpenSearch/pull/1003/commits/7c50669622b04f49be6d5df14b494ca69dcacaad the DCO check passed, but this wasn't a valid e-mail address.

**Comment by peternied** [comment]
Email address validation could be added to this script that would detect scenarios like described above.  https://github.com/opensearch-project/OpenSearch/blob/main/dev-tools/signoff-check.sh

**Comment by dblock** [comment]
@peternied Is this something handled by the new DCO workflow you're rolling out?

**Comment by peternied** [comment]
The new DCO workflow does perform a validation under the covers with [email-validator](https://www.npmjs.com/package/email-validator), super deep [details](https://github.com/manishsaraan/email-validator/blob/master/index.js#L3).

The email address in this bug is still considered valid according to that library.  Something is better than nothing.

I'm going to resolve this when that pull request goes in.
