### ISSUE TITLE
[Vote][Proposal] Release OpenSearch/Dashboards Multi-Arch Docker Images

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#105]
## What kind of business use case are you trying to solve? What are your requirements?
[Proposal] Release OpenSearch/Dashboards Multi-Arch Docker Images
Issue: #30 

We would like the community to help us with the release.
Please use emotes 1️⃣ or 2️⃣ to record your vote.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
We have created multi-arch docker image with both `x64` and `arm64`, and have deployed to **opensearchstaging** repository. These images also consume the latest enhancements/fixes in #93 #95.
![Screen Shot 2021-07-23 at 8 08 06 PM](https://user-images.githubusercontent.com/65193828/127194082-74cf4d8e-715e-4ed2-bb19-1c9c2275581d.png)
![Screen Shot 2021-07-23 at 8 24 49 PM](https://user-images.githubusercontent.com/65193828/127194138-6075ce58-d892-4ccf-87a7-adcccc57ef1b.png)

```
docker pull opensearchstaging/opensearch:1.0.0-multi-test
docker pull opensearchstaging/opensearch-dashboards:1.0.0-multi-test
```

We would like to release OpenSearch/Dashboards Multi-Arch Docker Images to production repository (**opensearchproject**).

There are two options right now:
(1️⃣) Release it now with the same `1.0.0` tag, this would overwrite the existing `1.0.0` tag.
(2️⃣) Release it during new upcoming `1.1.x` release, this would delay the release but would not overwrite existing tags.

**What are your assumptions or prerequisites?**
Describe any assumptions you may be making that would limit the scope of this proposal.

**What are remaining open questions?**
List questions that may need to be answered before proceeding with an implementation.

**Comment by rursprung** [comment]
even though i'm not using these docker images: 2️⃣ for the simple reasons that users of the docker image must trust that the image with a specific tag doesn't just magically change. some might even have checksum validations in place (i.e. pull the image, run all the security scans on it and then get the checksum) or have a local copy thereof (so they wouldn't even notice if you replace the image because they stick to the old one).
IMHO it's a big no-go to _ever_ replace a once-released package (you also don't force-push to your release branches in git, do you?). at most you can yank an old version if you want to prevent everyone from using it for some reason (e.g. if it has a security issue).

**Comment by peterzhuamazon** [comment]
Thanks @rursprung for the advices will keep monitoring.

**Comment by peterzhuamazon** [comment]
We are releasing this in 1.1.0 release.
