### ISSUE TITLE
OpenSearch minimal (min) docker image missing on dockerhub

### ISSUE THREAD

**Issue by frotsch** [opensearch-project/opensearch-build#119]
Seems there is no minimal (min) docker image on dockerhub?

That would be helpful for development for integration testing purposes.

Pls. publish the minimal image for every release alongside with the default docker image on dockerhub

**Comment by dblock** [comment]
Moved this into https://github.com/opensearch-project/opensearch-build

**Comment by stockholmux** [comment]
@frotsch  For dev and integration testing, is it possible provide configuration file (`opensearch.yml`) in your use case?

**Comment by peternied** [comment]
[Triage] @bbarani Can you weigh in on this issue?

**Comment by bbarani** [comment]
@frotsch Do you still see a need to publish -min images to Docker?

**Comment by frotsch** [comment]
yes

**Comment by bbarani** [comment]
Closing this issue as we dont have plans to support this feature in near future.

**Comment by dblock** [comment]
@bbarani This is a valid feature request, let's leave it open?

**Comment by dblock** [comment]
After some digging on the issue (thanks @jules and @stockholmux for pointing me to the history) I think we did the right thing to close this as "won't do". The topic has been discussed [here](https://discuss.opendistrocommunity.dev/t/convergence-of-opensearch-opendistro-plugins/5625/44). In short, `-min` isn't a desired production distribution, since it has no security and we only offer it as .tgz, with caveats on the download page. Happy to hear other opinions and change my mind.
