### ISSUE TITLE
Create an account at crates.io to publish artifacts of Rust Client

### ISSUE THREAD

**Issue by adityaj1107** [opensearch-project/opensearch-build#1199]
We need crates.io account to publish the artifacts of the opensearch rust client for community consumption. Please help create this account.

**Comment by aditjind** [comment]
Repo for which artifacts need to be published: [opensearch-rs](https://github.com/opensearch-project/opensearch-rs)

**Comment by gaiksaya** [comment]
[Offline Discussion] @aditjind is figuring out how to sign and publish the artifacts on crates.io
https://doc.rust-lang.org/cargo/reference/publishing.html
On glancing at the above document looks like the process can be automated. We can use `opensearch-ci-bot` as the GH account required to publish to crates. Need to check with the permissions and stuff.
However, since we are running short on time @aditjind requested to publish the initial version of client using manual documented process. He will work parallely on automating this for future releases.
The automation would include adding a jenkins workflow for opensearch-rs that will have right set of credentials to publish.
cc: @bbarani

**Comment by VijayanB** [comment]
@gaiksaya In the meantime, shall we create an opensearch-project account and use that to publish either manual or automation.

**Comment by gaiksaya** [comment]
> @gaiksaya In the meantime, shall we create an opensearch-project account and use that to publish either manual or automation.

I do not see an option to create a new account. All see is `Log in with GitHub`. Am I missing something here?

**Comment by bbarani** [comment]
@aditjind @VijayanB Can we directly link opensearch-ci-bot GitHub account with crate.io and publish the artifacts?

**Comment by aditjind** [comment]
As per my understanding, we will use the opensearch-ci-bot GitHub account to publish the first release of the client manually. We will then have automation scripts to build, sign and publish the artifacts via Infra Jenkins setup. 
cc: @gaiksaya (Correct me if I missed anything).

**Comment by aditjind** [comment]
No staging area support for Crates:

* [Issue](https://github.com/rust-lang/crates.io/issues/1503) 
* [Discussion](https://github.com/rust-lang/crates.io/discussions/4330)
