### ISSUE TITLE
[Enhancement]Add arm64 specific binary to ci-runner arm64 images

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1206]
### Is your feature request related to a problem? Please describe

As of now the ci-runner images for al2 and centos7 are installing cypress@6.9.1 through npm/yarn.
x64 version is ok but arm64 version will not run because cypress does not have arm64 binary yet.

@joshuali925 has manually compiled a cypress@5.6.0 for arm64 which proved to run well in #567 #1118 

We have uploaded this version to https://ci.opensearch.org/ci/dbc/tools/Cypress-5.6.0-arm64.tar.gz

We need to tweak the ci runner dockerfile so that it will install both arch with cypress@5.6.0 and then replace the arm64 one with the tarball above.

The only plugin as of now has issues with cypress@5.6.0 on arm64 host is AD Dashboards plugin, where @ohltyler needs to have some research.

Thanks.

### Describe the solution you'd like

See above.

**Comment by joshuali925** [comment]
For some context, the binary was built using cypress tag 6.8.0 targeting 5.6.0, because version 5 uses `node-sass` which doesn't work well on arm64. This version difference didn't affect our plugins, but I don't know if it will cause issues for others.

Might be better to upgrade to cypress 6 or above and make the version consistent for all plugins. Building cypress 6 on arm64 is easier, we just need to skip puppeteer chromium and link a prebuilt like [the one from reporting](https://github.com/opensearch-project/dashboards-reports/releases/download/chromium-1.12.0.0)

**Comment by peterzhuamazon** [comment]
> For some context, the binary was built using cypress tag 6.8.0 targeting 5.6.0, because version 5 uses `node-sass` which doesn't work well on arm64. This version difference didn't affect our plugins, but I don't know if it will cause issues for others.
> 
> Might be better to upgrade to cypress 6 or above and make the version consistent for all plugins. Building cypress 6 on arm64 is easier, we just need to skip puppeteer chromium and link a prebuilt like [the one from reporting](https://github.com/opensearch-project/dashboards-reports/releases/download/chromium-1.12.0.0)

There are some plugins such as AD is still relying on 5.6.0.
I will try to create an image and see if it runs.
I will talk to you @joshuali925 about creating 6 if needed.

Thanks.
