### ISSUE TITLE
Publish human-readable test run reports as a simple HTML document

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#130]
Publish the performance testing results

**Comment by camerski** [comment]
All test results should be stored in the same location as the bundle. The testing workflows should be given a path to a bundle manifest, for example `s3://bucket/path/to/bundles/1/manifest.yml`, load all the information they need from that manifest, and write results back to a sub-folder (e.g. `s3://bucket/path/to/bundles/1/test_results/performance_tests`).

This should work for, at minimum, S3 locations and local filesystem locations (i.e. `file://` URLs).

**Comment by dblock** [comment]
@gaiksaya looking at https://github.com/opensearch-project/opensearch-build/pull/366 can you please elaborate on what we're trying to do?

I am told the perf test API only outputs JSON? Is this true? How did we use those results in the past? Who looks at these results? 

It strikes me that it's unlikely that the tool doesn't already produce humanly readable results, or that we aren't adding the feature to the tool instead of doing JSON to HTML conversion in our build infrastructure.

**Comment by peternied** [comment]
I believe surfacing the json is more than enough for right now.  Performance reporting which can including tracking and comparisons is a significant amount of work

**Comment by saratvemulapalli** [comment]
Closing this as the change is merged.
