### ISSUE TITLE
Rename maven-signed to opensearch-signed/maven

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1398]
### Is your feature request related to a problem? Please describe

When signing artifacts, in S3 the signed artifacts are written to `maven-signed` next to `opensearch`, which is inconsistent.

### Describe the solution you'd like

Renamed `maven-signed` to `opensearch-signed` and `opensearch-dashboards-signed` or something like that.

**Comment by zelinh** [comment]
[Triage] Since a lot of jenkins job are relying on the folder name `maven-signed` on S3 to find the created artifacts, we need to approach this with caution. For example, opensearch-java, opensearch-bundle-maven, opensearch-ruby, etc.. All these jobs have to be changed corresponding to the name change.

**Comment by gaiksaya** [comment]
We are not uploading the signed maven artifacts to S3 any more. The artifacts are signed and directly uploaded to maven central now.
Closing this issue. 
Thanks!
