### ISSUE TITLE
[Bug]: Circular dependency on job-scheduler-spi SNAPSHOT

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1463]
### Describe the bug

There's a circular dependency on -SNAPSHOT builds being published to maven that require the distribution build to be successful.

### To reproduce

1. In order to build anomaly-detection job-scheduler-spi SNAPSHOT is required, e.g. https://github.com/opensearch-project/anomaly-detection/pull/360 that is failing because job-scheduler-spi in maven is not up-to-date
2. In order to publish job-scheduler-spi SNAPSHOT to Maven a successful distribution build is required
3. The distribution build is failing because anomaly-detection cannot be built, because of (1)

### Expected behavior

We shouldn't be able to get into this situation. Most likely this means we need to change our distribution build to publish snapshots after each component is built, and not at the end.

### Additional context

To work around this problem we have to break the circular dependency temporarily:

1. Remove the problematic component from the build, e.g. https://github.com/opensearch-project/opensearch-build/pull/1462
2. Produce a successful distribution build without anomaly-detection
3. Fix the issue in anomaly-detection, e.g. make sure https://github.com/opensearch-project/anomaly-detection/pull/360 passes.
4. Re-add anomaly-detection to the distribution, e.g. https://github.com/opensearch-project/opensearch-build/pull/1464

**Comment by prudhvigodithi** [comment]
This is closely related to this issue https://github.com/opensearch-project/opensearch-build/issues/1366
Right now in the manifest we first build the Core, job-scheduler and common-utils and then update with other components. This is a known dependency model, in terms of automation what we can do is, since we have a `--component` feature in now for build workflow, we can onboard all the components in the manifest and build in an order.
1st run would be `--component OpenSearch job-scheduler common-utils`. 
@dblock @bbarani @peterzhuamazon

**Comment by jordarlu** [comment]
Hi, team, just to quick check if this is still a valid issue/blocker, and if we can close it now ... thanks!!

**Comment by jordarlu** [comment]
I am closing this issue for now .. pls re-open/create a new one if needed,,, thanks !!
