### ISSUE TITLE
[RPM M6] Validate package installing

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1555]
Tasks | Estimate | Status | Notes | Dependencies
-- | -- | -- | -- | --
Install rpm through local yum repository | 1 | No Plan |   | All of these requires us to create pipelines to automatically run these tests for validations
Install rpm through remote yum repository | 1 | Complete |   | All of these requires us to create pipelines to automatically run these tests for validations
Install rpm through installing the package directly without yum | 1 | Complete |   | All of these requires us to create pipelines to automatically run these tests for validations

* https://github.com/opensearch-project/opensearch-build/pull/1912

**Comment by zelinh** [comment]
Our automatic RPM distribution have mostly completed for OpenSearch distribution and we are working on the validation for the OpenSearch Dashboards distribution. Since the dashboards needs OpenSearch installed and running for validation so we plan to use the latest opensearch rpm distribution. We would need a running distribution build workflow for latest OpenSearch distribution to run the validation for dashboards. We are actively working on this.

**Comment by peterzhuamazon** [comment]
Add systemd for rpm to run on it: https://github.com/opensearch-project/opensearch-build/pull/1958

**Comment by peterzhuamazon** [comment]
@zelinh will add jenkinsfile to use the libs committed in #1912.

**Comment by peterzhuamazon** [comment]
Add to distribution:
* https://github.com/opensearch-project/opensearch-build/pull/2021
