### ISSUE TITLE
1.3.0 distribution builds failing due to Shadow plugin gradle version bump

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-build#1587]
Common utils is not upgraded to Gradle 7, which is causing this failure when trying to build the common-utils component for 1.3.0:
```
FAILURE: Build failed with an exception.
 
* Where:
Build file '/tmp/tmp5rc4dbsg/common-utils/build.gradle' line: 67
 
* What went wrong:
A problem occurred evaluating root project 'common-utils'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin']
  ​> This version of Shadow supports Gradle 7.0+ only. Please upgrade.
```

This failure occurred after the Shadow plugin bumped to Gradle 7.0+ as part of this PR: https://github.com/opensearch-project/OpenSearch/pull/2033

Tracking issue in common-utils: https://github.com/opensearch-project/common-utils/issues/101

**Comment by saratvemulapalli** [comment]
Thanks @ohltyler for reporting this.
This is due to OpenSearch moving to a new version of Shadow plugin due to Log4J CVE. 
Ref: https://github.com/opensearch-project/OpenSearch/pull/2033

I see couple of options:
1. If the plugin/library wants to use something exported by OpenSearch, they can continue to do so via upgrading gradle.
2. If not, they can explicitly add a dependency for the older version of a shadow plugin. This includes fixing `common-utils`, `job-scheduler`, `alerting` and `notifications`. Ref: [Search link](https://github.com/search?q=org%3Aopensearch-project+com.github.johnrengelman.shadow&type=code)
3. Revert the change on 1.x line of OpenSearch

@ohltyler @dblock @reta what do you guys think?

**Comment by reta** [comment]
@saratvemulapalli I think we have to revert the change for 1.x (sadly), we cannot break existing plugins. The same discussion we have had with @dblock when we were updating to Gradle 7.x: it was a breaking change for 1.x so the strong point was made to keep the promise and never make breaking changes within minor / patch releases (as such, 1.x is still on Gradle 6.x). Thank you.

**Comment by saratvemulapalli** [comment]
Thanks @reta ! I agree. 
I did put up a PR to revert the change in 1.x. 
https://github.com/opensearch-project/OpenSearch/pull/2047

**Comment by saratvemulapalli** [comment]
The change is merged. 
Closing the issue.
