### ISSUE TITLE
[Bug]: postCleanup utility does not remove files when run with root

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1813]
### Describe the bug

Running a Jenkins job with `root` access prevents the `postCleanup` from deleting the workspace.

### To reproduce

Run a job with the following agent:

```
    agent {
        docker {
            label 'Jenkins-Agent-al2-x64-c54xlarge-Docker-Host'
            image 'opensearchstaging/ci-runner:ci-runner-ubuntu2004-data-prepper-pipeline-v1'
            alwaysPull true
            args '-u root'
        }
    }
```

### Additional context

See the following discussion:

https://github.com/opensearch-project/opensearch-build/pull/1803#discussion_r833520179

**Comment by zelinh** [comment]
[Triage] We have been aware that this is a valid issue. Remove the untriaged label now.

**Comment by zelinh** [comment]
@dlvenable What's point of cleaning the workspace if the image will be removed after the process?

**Comment by zelinh** [comment]
Close this issue for now since we currently add commands to remove workspace files if using root access to docker images. Feel free to re-open if necessary. 
E.g. 
https://github.com/opensearch-project/opensearch-build/blob/a257f9b977ea5b16a34ada6ab0b37ee447641b70/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile#L157
