### ISSUE TITLE
Automate creation of releases (on github) after every release when the release tag is created

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1898]
### Is your feature request related to a problem? Please describe

We manually create the releases (on github) for opensearch and plugins. We want to automate this after a the release once the release tags are created.

### Describe the solution you'd like

Add functionality to the [release tag job](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/release-tag/release-tag.jenkinsfile) to be able to add releases for opensearch and all the plugins.

### Acceptance Criteria
- [ ] The releases are created automatically using the release tags job for opensearch, opensearch-dasboards and plugins

**Comment by zelinh** [comment]
I think in order to implement this automation. We will need to standardize our GitHub Releases contents for each release. We will need to decide what we want to include in our Release section. e.g. link or contents of the release notes, download links from `opensearch.org` for OpenSearch and OpenSearch Dashboards; source codes(.zip & .tar.gz) as assets. I also noticed GitHub action was used to create the Release in some repos on some release version. We could possibly elaborate on that approach.
After we finalize this design part, we could work on this automation across all OpenSearch repos.

**Comment by bbarani** [comment]
@saratvemulapalli will be creating campaigns to track the effort involved in automating the release tags for 2.2 release.

Sample PR: https://github.com/opensearch-project/OpenSearch/pull/3813

**Comment by bbarani** [comment]
@saratvemulapalli any update on creating campaigns for this effort?

**Comment by saratvemulapalli** [comment]
@bbarani looks like it fell through the cracks. I'll take care of this.

**Comment by saratvemulapalli** [comment]
We have our first automated github release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

**Comment by saratvemulapalli** [comment]
@zelinh @bbarani I'm adding up documentation.
https://github.com/opensearch-project/opensearch-plugins/pull/198
Once the PR is in i'll create a campaign across the project.

**Comment by zelinh** [comment]
Thanks @saratvemulapalli. Really great for bring this across plugins repos.

**Comment by saratvemulapalli** [comment]
Campaign is up: https://github.com/opensearch-project/opensearch-plugins/issues/201
