### ISSUE TITLE
Generated manifests for OpenSearch 2.x need custom JAVA_HOME

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2044]
### Is your feature request related to a problem? Please describe

Automation opened a PR to generate the OpenSearch 3.0 manifest. That manifest was missing `JAVA_HOME` that was added manually in https://github.com/opensearch-project/opensearch-build/pull/2042.

### Describe the solution you'd like

Add a way to customize generated manifests for various products/versions, add `JAVA_HOME` to the OpenSearch ones.

### Describe alternatives you've considered

Keep doing it manually.

**Comment by peterzhuamazon** [comment]
We just need the manifest workflow to add this line for OpenSearch BE.
The problem being we can only default to the highest java version tho.

**Comment by dblock** [comment]
There's some hard-coding going on in https://github.com/opensearch-project/opensearch-build/blob/3b65a0a9803f53d4ad1bb4c51763748150fb9bd0/src/manifests_workflow/input_manifests.py#L108 that will need refactoring.

**Comment by prudhvigodithi** [comment]
[Triage] just a thought since the the build container already has multiple java versions added, we might need to add an entry to manifest file that has JDK version specification, just like we have one for [checks:](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-2.0.0.yml#L14), so that way each component can use the desired java version that is passed, if not it will go withe default JDK version.

**Comment by zelinh** [comment]
Instead of hard-coding both `image_map`, `jdk_version` and `data: Dict = ...`, we are looking into an alternative way to auto generate the manifest with those data. As @dblock suggested [here](https://github.com/opensearch-project/opensearch-build/pull/2354#pullrequestreview-1045565801), I will be trying to create such template manifest folders and have the new manifest loading those infos depending on the product and version. If it doesn't have certain template, we will use hard-coded default value.

**Comment by gaiksaya** [comment]
Closing via https://github.com/opensearch-project/opensearch-build/pull/2358
