### ISSUE TITLE
Need to establish a code freeze mechanism

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#2052]
### Is your feature request related to a problem? Please describe

During the distribution release process, there is a milestone for feature freeze, representing the completion of all new features.  It is expected that bugs will be reported, triaged, and resolved due to integration testing.  After a time period a release candidate is picked by the distribution release owner.

If one of the components pushes a change to a version-number branch they could includes changes that are not intended to be part of the release if another release candidate is created.

### Describe the solution you'd like

We need a mechanism to `mark` a release candidate build and if we create another build, a way to be sure only intended changes go into it. For repeatability this process should have automated to support it to generate ensure consistent results.  

### Additional context

Following up from the great conversation about release milestones https://github.com/opensearch-project/.github/pull/65

**Comment by peternied** [comment]
### [Proposal] Use `./build.sh {manifest} --lock`
The build process can generate stable references for all manifest components.  A release candidate can be locked in place by running the following process;
* You want to code freeze to ensure no more changes are introduced
* fetch the most recent version of opensearch-build
* `./build.sh {manifest} --lock`
* `mv {manifest}.lock {manifest}`
* Commit and create a pull request of these changes.
* Review and merge.
* Builds for that manifest will automatically stop because the stable version will stay the same
---
* You want to add a bug fix(es) to an existing release candidate
* fetch the most recent version of opensearch-build
* Go to {manifest}, update only the component github ref to the expected values.
* Commit and create a pull request of these changes.
* Review with all updated components, make sure only expected changes are in before merging.
* Built for new RC will automatically be created because stable version was updated.

**Comment by dblock** [comment]
The idea of code-freeze seems that there's a few days after we say "code freeze" where nothing is merged onto a release candidate branch (e.g. 2.0). This feels like a mistake. Our main problem is that it takes > 1 day to take a given build and run non-automated processes against it, in order to evaluate whether that build is good enough for an RC. If that could be done quickly, we would not need to freeze anything.

**Comment by bbarani** [comment]
@dblock this is not the main problem "Our main problem is that it takes > 1 day to take a given build and run non-automated processes against it, in order to evaluate whether that build is good enough for an RC." The main issue is the fact that there is always a chance that we would need to re-generate RC for various reasons (ex: Found a critical bug fix at the last minute after finalizing RC, critical CVE etc..) and we are trying to avoid more moving parts in those scenarios. I would recommend to come up with a process to avoid any new merges between finalizing RC to release timeline. Having said that, I would also keep the window between RC and release as minimal as possible (max 1 to 2 days( to avoid delaying merges for very long time.

**Comment by dblock** [comment]
I guess we disagree on approach. I'd prefer a train model, and not to have "and we are trying to avoid additional scope / moving parts in those scenarios", projects that make up the distribution should be able to put bug fixes in for as long as they like and those can absolutely be piled up between the first RC candidate, and the second RC candidate. We pick a build, we test, we find it's not good enough for RC, then we pick the next build (that has half a dozen bug fixes), and we iterate with a full set of tests.

**Comment by bbarani** [comment]
@dblock I am ok with adding bug fixes but not backports that introduces any additional scope not planned for a specific release. We are technically getting in to the zone of "scope creep" when we allow that to happen. This will create a cyclic dependency and never ending RC build generation process. We create a finalized RC build, some team reports an issue and apply bug fix. We create a new RC but that has some additional code changes that causes new issues (and also not make the actual bug fix work) and that cycle goes on forever.

**Comment by dblock** [comment]
> @dblock I am ok with adding bug fixes but not backports that introduces any additional scope not planned for a specific release. 

I agree. I can see how someone can slide a feature in, but I am not seeing what prevents this from happening right now: you declared an RC and stopped building, I can still go commit a feature, and hope you discard the RC and pickup the next build. What I am saying is that code freeze is not a mechanism right now either.

**Comment by peternied** [comment]
@bbarani @peterzhuamazon I believe there was a new manual process around how to establish code freeze earlier this week.  Maybe we could pick this up to codify the process with a degree of automation, or maybe you've got a better recommendation  since we've learned a lot since the issue was opened.

**Comment by bbarani** [comment]
Closing this issue as we have already added guard rails to build the RC based on commit rather than a branch.
