### ISSUE TITLE
Support release process for spring-data-opensearch

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-build#2846]
### Is your feature request related to a problem? Please describe

We have a new repository https://github.com/opensearch-projectspring-data-opensearch to support OpenSearch integration with Spring projects ecosystem (based on Spring Data Elasticsearch).

### Describe the solution you'd like

The release process is not yet in place, the artifacts are: signed JARs under `org.opensearch.client` group (Sonatype or alternative public Apache Maven repositories).

### Describe alternatives you've considered

N/A

### Additional context

The release / snapshots Jenkins jobs are ready: https://github.com/opensearch-project/spring-data-opensearch/pull/46

**Comment by reta** [comment]
CC @peterzhuamazon

**Comment by prudhvigodithi** [comment]
[Triage]: This can added as part of [universal release mechanism](https://github.com/opensearch-project/opensearch-build/issues/1234) with maven.

**Comment by dlvenable** [comment]
@prudhvigodithi , What is the timeframe for the universal release mechanism? The spring-data-opensearch project is ready for -SNAPSHOT releases now and probably almost ready for the 0.1 release as well. I'd like to make the snapshots available to users so they can start giving feedback.

**Comment by dlvenable** [comment]
@prudhvigodithi , This spring-data-opensearch project's most similar project is opensearch-java. Whatever mechanism is in place for opensearch-java today may be usable for spring-data-opensearch.

**Comment by prudhvigodithi** [comment]
Thanks @dlvenable adding @gaiksaya and @peterzhuamazon can we continue to use the same mechanism used at `opensearch-java`? 
@bbarani

**Comment by gaiksaya** [comment]
Hey! I'll update this issue on 11/21 after discussing few pointers with the team.
Thanks!

**Comment by reta** [comment]
FYI, the Jenkins files are PRed https://github.com/opensearch-project/spring-data-opensearch/pull/46

**Comment by gaiksaya** [comment]
Adding some details here. 

We have Publish to Maven lib ready https://github.com/opensearch-project/opensearch-build/issues/2398 however some minor bugs were discovered during testing which @rishabh6788 is working on this fix. 
The snapshot publishing feature will be added as a part of the same workflow. 

As stated in universal release diagram we will be not building any artifacts on the system since the CI system and release systems are different and can lead to discrepancies in the artifacts shipped to the customer. Please see https://github.com/opensearch-project/opensearch-build/issues/1234 for details. 

Question regarding the release @reta @dlvenable I see there are multiple components in that repository like 

- [spring-data-opensearch-starter](https://github.com/opensearch-project/spring-data-opensearch/tree/main/spring-data-opensearch-starter)
- [spring-data-opensearch-test-autoconfigure](https://github.com/opensearch-project/spring-data-opensearch/tree/main/spring-data-opensearch-test-autoconfigure)
- [spring-data-opensearch](https://github.com/opensearch-project/spring-data-opensearch/tree/main/spring-data-opensearch)
Will all of them be released at the same time always? Or is there a possibility of releasing them independently in future?

**Comment by reta** [comment]
> * Will all of them be released at the same time always? Or is there a possibility of releasing them independently in future?

Thanks @gaiksaya , they all will be released at the same time (or none).

**Comment by gaiksaya** [comment]
Hi @reta ,

The spring data OpenSearch repo is set for the release. We have added the webhook and the job to be monitored is here https://build.ci.opensearch.org/job/spring-data-opensearch-release/

When are you planning to push a tag?

**Comment by gaiksaya** [comment]
Spring data opensearch 0.1.0 is released now: https://repo1.maven.org/maven2/org/opensearch/client/

**Comment by gaiksaya** [comment]
Hi @reta,

You can now publish snaphots to maven using GHA directly. See the PR[1] as an example on what all needs to be added to make that happen. You can add me as a reviewer once PR is ready so that I can make changes at the backend and add the required role to retrieve the credentials.
Thanks!

[1] https://github.com/opensearch-project/opensearch-java/pull/325

**Comment by reta** [comment]
This is awesome, thanks a lot @gaiksaya ! I will take it shortly
