### ISSUE TITLE
[Retrospective] Release 2.4.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2905]
How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by ohltyler** [comment]
I've added #2949 to discuss enforcing post-release activities

**Comment by gaiksaya** [comment]
The version bump PRs which are automated for OpenSearch today and yet to be automated for Dashboards need to be reviewed on time rather than waiting for release to come closer. 
The compatibility as well as other issues can be discovered sooner than later and reduces last min chaos and friction in the release process.

**Comment by macohen** [comment]
Having an updated reference repository of actions to use in a brand new repository may have helped make the process of including new plugins in the build smoother with some less back and forth. Checklists have also helped here so there's been some good progress.

**Comment by bbarani** [comment]
Review comments has been noted and we will work on automating the PR version bump for OpenSearch dashboards and improve on-boarding documentation.
