### ISSUE TITLE
Suggested Improvements to Release Template

### ISSUE THREAD

**Issue by macohen** [opensearch-project/opensearch-build#2924]
When this issue is created in the target repos, it would be helpful to have some more detail, especially if it is for a new repo. Setting up codecov, dependabot, actions, backporting needed handholding from the release team that may not have been necessary if there was a link to another checklist for new repos. Also, the first step in post release may be clarified with an example. For example: "Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version."  could be changed to " Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version. (e.g. after release of 2.4, the 2.4 (release) branch should build 2.4.1, the 2.x branch should build 2.5.0")

https://github.com/opensearch-project/opensearch-build/blob/main/meta/templates/releases/release_template.md

**Comment by jordarlu** [comment]
Hi, @macohen, since the time this issue got opened, the release template has been improved a few rounds, and also got moved to here https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md , also, the team adds a [Wiki page](https://github.com/opensearch-project/opensearch-build/wiki/Releasing-the-Distribution) to describe the process and explain the flow ,, I am so sorry that we replied just now, would you mind have a look and let us know if the current design works ok?  thanks!!

**Comment by macohen** [comment]
Thanks! I totally didn't remember opening this issue, but we've come along way. The detail is much improved. I'll close!
