### ISSUE TITLE
Verify the artifacts in maven nexus releases repo.

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#2928]
Validate the artifacts and associated contents on Maven

Acceptance criteria:
- [x]  Every .jar came with a corresponding .md5 and .sha1 signature file.
- [ ] Every artifact comes with a corresponding sources jar.
- [ ] Every artifact comes with a corresponding javadoc jar.
- [ ] POM contains project name, description, URL, license information, SCM URL, and developer information.

 (or)

Acceptance criteria:

If we can have both the [snapshot repo](https://aws.oss.sonatype.org/content/repositories/snapshots/) and [releases repo](https://aws.oss.sonatype.org/content/repositories/releases/) the same upload artifact rules (https://central.sonatype.org/publish/requirements/), then we can identify the  validation issues early even before uploading to central maven.

**Comment by bbarani** [comment]
@gaiksaya @peterzhuamazon @prudhvigodithi Is this issue still valid?

**Comment by prudhvigodithi** [comment]
`Every .jar came with a corresponding .md5 and .sha1 signature file.`
This is taken care by the automation once we promote to maven

`Every artifact comes with a corresponding sources jar and javadoc jar.`
As of now adding the sources jar and javadoc jar logic comes from plugin team (majority using https://imperceptiblethoughts.com/shadow/introduction/ ) and every plugin is honoring this because of the requirement for publishing to maven. https://central.sonatype.org/publish/requirements/

` POM contains project name, description, URL, license information, SCM URL, and developer information.`
This check we dont have today and the contents of the xml are controlled by the plugin level gradle file.
We can check https://maven.apache.org/archives/maven-1.x/plugins/pom/validation.html

So above these checks we should have a checks at higher level that can detect/validate maven pom file, the maven co-ordinates and if the co-ordinates having the expected artifacts.

**Comment by gaiksaya** [comment]
Apart from plugins we also publish a number of stand alone components on maven that do not extend core's plugin framework. I believe we still need to have checks for all of above points. Have seen before that jars are missing the corresponding sources and javadoc jars. 
POM validation is also required for sure.

**Comment by gaiksaya** [comment]
Hi @prudhvigodithi , @dblock, @reta ,

We have faced issues in the past where the maven publication to sonatype fails because of missing properties like pom is missing project description, etc. 
I see that there is a task called `validateNebulaPom` in all plugins' gradle files that is disabled: https://github.com/search?q=org%3Aopensearch-project+validateNebulaPom.enabled&type=code&p=1

Wondering if you have any idea if enabling it would automatically validate the POM and fail early rather than in the last step of release cycle?
Thanks!

**Comment by reta** [comment]
> Wondering if you have any idea if enabling it would automatically validate the POM and fail early rather than in the last step of release cycle?

Thanks @gaiksaya , I believe there is an issue with nebula and maven POM publications we are running into, that's is why it is disabled in most (if not all) plugins, sadly

**Comment by prudhvigodithi** [comment]
Thanks @gaiksaya, as a quick fix we can have both the [snapshot repo](https://aws.oss.sonatype.org/content/repositories/snapshots/) and [releases repo](https://aws.oss.sonatype.org/content/repositories/releases/) the same upload artifact rules at the package level `org.opensearch` (Just to make sure adding this rule wont break the other packages as the [snapshot repo](https://aws.oss.sonatype.org/content/repositories/snapshots/) hosts more packages other than just OpenSearch related), so that we can detect the POM failure at early stage.

**Comment by gaiksaya** [comment]
I created an issue with sonatype for the above request: https://issues.sonatype.org/browse/OSSRH-98148
Looks like the validation ruleset is only available for maven central non-snapshot artifacts. However, the work around suggest in the ticket should be possible. During RC creation, one of the step would be to upload to nexus sonatype, close the repository (which will run all the checks) and then drop it. 
Its a risky move but would save us from over engineering the validation. Also if any rules change from maven central's side, it would be caught too. 
Let me know what you think. @prudhvigodithi @bbarani 

Thanks!

**Comment by zelinh** [comment]
AFAIK, maven snapshot artifacts are uploaded from each plugin side. They have GHA to publish maven snapshot to Sonatype for 2.x. We are publishing release maven artifacts through our Jenkins workflow.

Are you suggesting we can create a mock maven release workflow which could be run especially during release cycle; basically it will skip this part https://github.com/opensearch-project/opensearch-build-libraries/blob/120cc3ad30a8122c7c7662d61e488bf0aea3f18a/resources/publish/stage-maven-release.sh#L177-L190
and drop the staging repo instead?  @gaiksaya

**Comment by zelinh** [comment]
According to my research, `validateNebulaPom` doesn't load the `description` info from our current plugin repo, so it will always say that is missing and fail the task. 

However, for our plugin repo, we don't plugin `jar` with Nebula Pom so it's not necessary to validate it. That's why we disable it for all our plugin repos. 

For OS native plugins, we are publishing `jar` so it would be needed.

**Comment by zelinh** [comment]
Seeing this error when running `./gradlew validatePom`
```
    Reason: Task ':validateNebulaPom' uses this output of task ':generatePomFileForPluginZipPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

It seems like Gradle is assuming each validation task is depending on all the Pom generation tasks as implicit dependency. Gradle treats any task that reads a file as implicitly dependent on each task that writes to that file.

Since all `generatePomFileForPubNamePublication` create the Pom file writing to the same file location, we will need to declare implicit gradle dependency for all `generatePomFileForPubNamePublication` to `validatePubNamePom`.

**Comment by zelinh** [comment]
`validatePom` tasks are updated in OpenSearch core main branch and 2.x branch.
https://github.com/opensearch-project/OpenSearch/pull/12807
https://github.com/opensearch-project/OpenSearch/pull/12909

**Comment by zelinh** [comment]
Closing this issue as implementation is completed.
