### ISSUE TITLE
Request for build support of dashboards-notifications

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/opensearch-build#3056]
### Is your feature request related to a problem? Please describe

opensearch-project/notifications plugin has both back end and dashboards in a single [repo](https://github.com/opensearch-project/notifications) . We are splitting the dashboards part into its own repo - dashboards-notifications repo as requested [here.](https://github.com/opensearch-project/notifications/issues/466).

### Describe the solution you'd like

We have created a new repo - dashboards-notifications to support the front end in its own repo and we would like to have build scripts (of dashboards component) pick up the code from dashboards-notifications repo.

Back end plugin [repo](https://github.com/opensearch-project/notifications)
Dashboards [repo](https://github.com/opensearch-/dashboards-notifications)

### Describe alternatives you've considered

N/A

### Additional context

We will provide the links to PR after the codebase has been migrated to the new repo.

**Comment by gaiksaya** [comment]
Hi @praveensameneni ,

Making sure I understand it right, the dashboard-notification needs build scripts so that it can be built during distribution creation?
If that's the case, adding the `scripts/build.sh` in the root will do the trick. This is only required if your build script is customized in someway. 
Else if nothing is specified, default will be picked up from here https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/opensearch-dashboards/build.sh

However, I see a script for [notificationsDashboards](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/notificationsDashboards/build.sh) already exists in build repo. Would recommend to move it under new repo so that its easier to maintain on your end.

Thanks!

cc: @peterzhuamazon @prudhvigodithi Please correct if I am wrong.

**Comment by ansjcy** [comment]
FYI: After moving `dashboards-notifications` to its own repo, we saw some build and test failures. Here's [a related PR](https://github.com/opensearch-project/dashboards-notifications/pull/3) to fix the github workflow.

**Comment by bbarani** [comment]
Changes have been completed and we will close this issue after 2.5.0 is released
