### ISSUE TITLE
Custom jenkins job for running concurrent search tests

### ISSUE THREAD

**Issue by neetikasinghal** [opensearch-project/opensearch-build#3729]
### Is your feature request related to a problem? Please describe

Currently Search ITs do not run with Concurrent Search feature on the main branch as part of the gradle check. We are looking for a custom jenkins job that could run the tests with the feature flag on.

In order to run the tests, as of now, we need to run the command manually on the dev computer:
`./gradlew :server:internalClusterTest --tests "org.opensearch.search.*" -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true`

[Relates](https://github.com/opensearch-project/OpenSearch/issues/7440)

### Describe the solution you'd like

We would to have a jenkins job that can automatically run the tests with day with the feature flag on

**Comment by prudhvigodithi** [comment]
From the offline discussion if this automation can be solved with Github Actions (using default GitHub Runners) that can be managed by @neetikasinghal and team, then the Jenkins solution is not required.

@neetikasinghal and team, please test the execution using GH Actions https://docs.github.com/en/actions/quickstart and update with the results here.

Sample examples of how we use the GH Actions in the build repo:
https://github.com/opensearch-project/opensearch-build/tree/main/.github/workflows 

Adding @bbarani

**Comment by sohami** [comment]
1. We are working on concurrent segment search feature which is currently behind experimental flag. The changes with this feature will be exercised in all the search flow. So we want to run all the UTs and ITs in the OpenSearch repository with this feature flag enabled to catch all the issues.
2. Currently we have to do that manually and that takes lot of time to run all the tests locally each time and because of randomizations in the test it produces different failures which becomes hard to keep track of.


The ask is if we can setup some automation (using the existing Jenkins mechanism from EE team) to run it automatically either on some events or as a cron at regular cadence. The command that needs to be executed will be below:

```
./gradlew assemble
./gradlew test -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
./gradlew internalClusterTest -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
```

**Comment by neetikasinghal** [comment]
We were able to solve this via a github action: https://github.com/neetikasinghal/OpenSearch/actions/runs/5626243180/workflow

**Comment by bbarani** [comment]
Closing this issue as it was resolved using a different method.
