### ISSUE TITLE
[Bug]: Unable to diagnose integ-test failure from 2.10 build

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#3882]
### Describe the bug

When looking at an integration test auto-cut issues, I see that the cluster failed to start; however, there are no opensearch.log files or other resources for me to inspect to determine why the cluster didn't come up.

```
  ...
  File "/var/jenkins/workspace/integ-test@2/src/test_workflow/integ_test/service.py", line 132, in wait_for_service
    raise ClusterCreationException("Cluster is not available after 10 attempts")
test_workflow.integ_test.service.ClusterCreationException: Cluster is not available after 10 attempts
script returned exit code 1
```

### To reproduce

Looks like the opensearch cluster has some kind of problem when it is starting

### Expected behavior

There should be many different logs files and datasources that can be inspected by teams attempting to troubleshoot

### Additional context

See https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/activity runs 5396 -> 5401 have failed and are being attributed to the security plugin on this ticket [1].

- [1] https://github.com/opensearch-project/opensearch-build/issues/3883

**Comment by zelinh** [comment]
[Triage] We are aware of this issue and we would look into this. Thanks.

**Comment by jordarlu** [comment]
Hi, @zelin, have you got any progress on this issue, and if this issue is linked to https://github.com/opensearch-project/opensearch-build/issues/1274 ?  thanks ..

**Comment by zelinh** [comment]
I think this issue is more like an enhancement request than a bug issue. AFAIK, currently for our test workflow, if the cluster is not spun up, there is basically no `opensearch.log` generated because the cluster is not even there. Therefore our test recorder won't capture anything in this case. @gaiksaya I think you were mentioning we may be able to record some kind of logs through this testing which could be used for debugging the reason of unavailable cluster. Could you provide some thoughts here? @gaiksaya

**Comment by rishabh6788** [comment]
Will take a look at this.

**Comment by rishabh6788** [comment]
Closing this issue.
