### ISSUE TITLE
[Documentation] Have a better documentation and way to update and maintain it regularly

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3936]
### Is your feature request related to a problem? Please describe

This repository contains various aspects of distribution from building to releasing. We have various workflows, images and other components that is used for build, test and release. 
However, the documentation is distributed in various places. Example:

- README: https://github.com/opensearch-project/opensearch-build/blob/main/README.md
- Wiki: https://github.com/opensearch-project/opensearch-build/wiki
- Test workflow: https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/README.md
- Release process: https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md

As a community user it comes difficult to search for information and get what we are looking for. 

### Describe the solution you'd like

Move all the content to GitHub wiki. It is great place for "too much" information. The UI automatically lists the sub-topics and makes its easier to parse through the content.
One drawback is, wikis do not allow Pull Requests (yet!). However, there is a work around to automate updating wikis. See  https://nimblehq.co/blog/create-github-wiki-pull-request

### Describe alternatives you've considered

Keep what is it now.

**Comment by colossus06** [comment]
i think two or more contributor can work together to find a workaround for organizing the documentation to help community better.

**Comment by chawinphat** [comment]
I would be interested in working on this. If anyone else wants to do it with me, let me know.

**Comment by gaiksaya** [comment]
Thanks @chawinphat.Assigning this issue to you. Please comment the approaches you would like to move forward with before moving to implementation. 
If anyone else is interested in collaborating please comment on this issue.

**Comment by SachinSahu431** [comment]
Hi @gaiksaya @chawinphat!

The first comment suggested a [solution](https://nimblehq.co/blog/create-github-wiki-pull-request) that I tried to implement, but it did not work for me.

As an alternative, I tried using [github-wiki-action](https://github.com/Andrew-Chen-Wang/github-wiki-action), and it appears to be working. It involved creating a folder named `wiki` in root directory and adding a [workflow](https://github.com/SachinSahu431/opensearch-build/blob/main/.github/workflows/publish-wiki.yml).

Here is the wiki page: https://github.com/SachinSahu431/opensearch-build/wiki

One issue I observed is that [linkchecker workflow](https://github.com/SachinSahu431/opensearch-build/actions/runs/6585839173/job/17893017179#step:3:53) is failing due to [relative URLs](https://github.com/SachinSahu431/opensearch-build/blob/main/wiki/Home.md?plain=1#L10).

**Comment by chawinphat** [comment]
Hi @SachinSahu431 I'll take a look at this over the weekend, and will let you know any progress I make.

**Comment by chawinphat** [comment]
@SachinSahu431 I tested the solution you posted and I think it works nicely too. I started migrating some of the documentation to test out the formatting. 

I think we can link all the document on the home.md file instead of adding a sidebar, since we can organise to our liking instead of having it alphabetically sorted like this:
<img width="283" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/91317217/e7c6834f-0e7c-4275-b1a1-0b17a7a29768">


I sorted the different README files into their respective folders:
<img width="743" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/91317217/87333761-7bc0-4d2a-8aee-6c48014ae28f">

<img width="726" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/91317217/6767615c-ae30-405e-91eb-05fba1c68792">

**Comment by chawinphat** [comment]
@SachinSahu431 I've tried out your method and it looks good to me. I don't think we can use relative addressing since it will point to the .md file instead of the corresponding wiki page?

I have a somewhat working version [here](https://github.com/chawinphat/opensearch-build/wiki).
The only problem is that link checker is failing like you said. The problem is alot less severe if we do not include the main README.md file in our wiki. What are your thoughts?

**Comment by chawinphat** [comment]
@SachinSahu431  I talked to @gaiksaya and she said to PR the workflow and get tbe first page of the wiki up first. For the links, we should use the urls of files in the main branch of opensearch-build, similar to what you did with your `Page 2` example.
