### ISSUE TITLE
Performance degradation in Jenkins

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#4130]
### Describe the bug

Recently noticed OpenSearch CI [public Jenkins](https://build.ci.opensearch.org/) going down with 504 gateway timeout, this is blocking the OpenSearch CI workflows. The Jenkins also runs the OpenSearch [gradle check ](https://build.ci.opensearch.org/job/gradle-check/) during an Open PR and is being impacted due to 504 gateway timeout.
Previously seen some `OutOfMemoryError` issues but was fixed when updated the Jenkins GC settings https://github.com/opensearch-project/opensearch-ci/pull/353, but this time even though the memory is under control the jenkins process hangs (application not responding) and throws 504 gateway timeout error.

To Suspect the actual issue is with numerous call made to Jenkins to get the job status and view the test reports, jenkins uses actual file system in backend (that stores the data in organized deep nested tree structure) which is where jenkins is hanging when made multiple calls to fetch the test reports and view the job status.

### To reproduce

N/A

**Comment by gaiksaya** [comment]
We have started with cleanup for Gradle check jobs. The job count reached 27K+. Discarding builds older than 180 days. See https://github.com/opensearch-project/opensearch-build/pull/4128

**Comment by rishabh6788** [comment]
Updated JVM Parameters on the main node and restarted container. 

Updated Params:
```
JENKINS_JAVA_OPTS=-Xms4g -Xmx16g -Dhudson.model.ParametersAction.keepUndefinedParameters=true -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions
```

**Comment by rishabh6788** [comment]
Few observations on the jenkins issue, it has been running the longest so far without any issue. 
1. `docker stats` metric for memory includes `cache` also, that is why we see 80-90% utilization when actually it is much less. See https://github.com/hashicorp/nomad/issues/16230. Going forward let us not panic on seeing 99% memory utilization, check free -h to get the approx memory util or use the method provided in the linked issue to get the actual memory in use by docker container. 
2. After setting the heap to 16G the GC has been happening quiet regularly and fast. 
[root@ip-10-0-131-48 bin]# ./jstat -gcutil 9669
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT    CGC    CGCT     GCT
  0.00 100.00  89.70  59.88  87.81  75.64   1262   18.340     0    0.000    90    0.650   18.991
3. My theory is a combination of 65G heap and increased activity due to release caused a lot of work for the GC which caused really long pauses ultimately resulting in process to hang indefinitely. This is just a theory with no data to show (not sure if any heap dump is available when heap was 65G to confirm). Anecdotally, as part of AWS ElasticSearch oncall I used to work on a lot of red cluster issues, 90% of which were caused due to long GC pauses in under-scaled clusters. In our case the GC size is just too big, as per Cloudbees support the max should be set to 16G, if you need more then split the controllers. 

Let us observe jenkins behavior over the weekend to confirm this behavior. I have asked @divyaasm to close the open ticket so that she get paged whenever the issue happens next. I have take heap dump when I saw 90% memory usage as well but don't think that is going to help as it is not the actual consumption.

**Comment by jordarlu** [comment]
Performance degradation happend again at 2023-10-17 8:47:41 PM (UTC-07:00) 
Observed 502 errors in access log ; `docker stats` shown the MEM usage kept rising while the `free -h` shown still many avaliable

**Comment by prudhvigodithi** [comment]
Closing this issue as the jenkins performance issues have been remediated with adjusted the CPU/Memory thresholds and cleaning up the build logs. Sample PR https://github.com/opensearch-project/opensearch-build/pull/4128.
