### ISSUE TITLE
[On-boarding]: opensearch-flow-framework plugin

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#4209]
### What is the name of your plugin?

opensearch-ai-flow-framework

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-ai-flow-framework/

### Targeted release version

2.12.0

### What type of the plugin are we on-boarding?

OpenSearch

### Did you read the on-boarding document

Yes

### Does this plugin has all the necessary automated tests?

Not yet, in progress

### Have you completed the required reviews including Security reviews, UX reviews?

Not yet, in progress

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yes
![Screenshot 2023-11-13 at 12 22 32 PM](https://github.com/opensearch-project/opensearch-build/assets/16099877/240bee62-d1b1-4a44-bcc7-2d18ed6570ed)

### Additional context

The plugin would have an experimental release in 2.12 release.

**Comment by gaiksaya** [comment]
The I tried building this plugin. Just one issue, the plugin name does not match what is stated in the issue as well as repo name:

```
      plugins:
        - plugins/opensearch-flow-framework-2.12.0.0.zip
    version: 2.12.0.0
```
Please fix this. Thanks!

**Comment by gaiksaya** [comment]
We are waiting on repository name change to move forward. I was able to build the plugin into the distribution with default scripts so no additional build script required.

To-Do:
- The plugin needs to on-board to integration and BWC test framework so that it can be tested at the distribution level. 
- Complete security review
- Make sure the plugin is experimental only: https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#experimental-features

**Comment by bbarani** [comment]
**Note**: This is released in 2.12.0 as experimental feature.

**Comment by gaiksaya** [comment]
Hi,

In order to release this plugin as a part of the distribution, please make sure to onboard to distribution test workflow. See details here: https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution
Please note that this is a requirement and can be a blocker is the criteria is not met.

Thanks!

**Comment by gaiksaya** [comment]
Closing this issue as flow-framework is on-boarded to test workflow. https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.12.0/opensearch-2.12.0-test.yml#L31
It is failing right now and issue creation was blocked due to missing tag which has been added now. 
Thanks!
