### ISSUE TITLE
[BUG] Upgrade opensearch to version 2.10.0 failed with message fatal glibc error cpu does not support x86-64-v2

### ISSUE THREAD

**Issue by Aloush-ha** [opensearch-project/opensearch-build#4580]
**What is the bug?**
I had deploy opensearch with opensearch dashboard as container through docker-compose file in my VM 
now I have version 2.8
when I try update it to version 2.10 or 2.11, I got this message from container log

**fatal glibc error cpu does not support x86-64-v2**

**What is your host/environment?**
- Hypervision: Hyper V
 - OS: Ubuntu 20.04.5 LTS
 - Version focal

Docker version 24.0.7,

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   44 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:                        7
Hypervisor vendor:               Microsoft
Virtualization type:             full

what should I do for that
thank you

**Comment by peterzhuamazon** [comment]
We move from AL2 to AL2023 to increase glibc version and prepare for AL2 deprecation.

I am just surprised Ubuntu 20.04.5 LTS does not support it running on docker but we are using 20.04.6 so that maybe the issue? VERSION="20.04.6 LTS (Focal Fossa)"

This is more of a issue with https://github.com/amazonlinux/container-images or https://github.com/amazonlinux/amazon-linux-2023/, as opensearch is just using the existing image provided from them. I hope this is not a hardware issue specifically to your CPU tho.

You can test if you can run AL2023 image on your server to verify this. Thanks.

**Comment by peterzhuamazon** [comment]
Close this issue for now as the base OS image upgrade is planned and we will keep use AL2023 for the time being on 2.10+.

Feel free to re-open this issue if needed.

Thanks.
