### ISSUE TITLE
[BUG] Manifest workflow failed due to increase of minimumCompileVersion of Java update in 2.x

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4952]
https://github.com/opensearch-project/OpenSearch/commit/399c646bcc5b351edf0697864a9b416f8c411b04

This has triggered a wave of failure in manifest-update workflow specifically on OpenSearch 2.x branch.

Starting here: https://build.ci.opensearch.org/job/manifest-update/506/console

------

PRs:
* https://github.com/opensearch-project/OpenSearch/pull/15307
* https://github.com/opensearch-project/opensearch-build/pull/4953

**Comment by prudhvigodithi** [comment]
Looks to me like an issue with `jdk11` coming from https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/manifests-update.jenkinsFile#L25?
Because the `./gradlew properties -Dbuild.snapshot=false` for OpenSearch `2.x` works on my local with `jdk21` and for `jdk11` I get an error `* What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0`, the same shows in the build log https://build.ci.opensearch.org/job/manifest-update/506/console.

**Comment by peterzhuamazon** [comment]
Seems like it:

Right now build dep and runtime dep is using different version now.

Runtime dep min is still 11: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/#java-compatibility

Build time dep min is now 17 minimum: https://github.com/opensearch-project/OpenSearch/pull/15267

**Comment by reta** [comment]
Yes, it could be extracted from `minimumCompilerVersion` file

**Comment by peterzhuamazon** [comment]
Re-open as it is not fixed permanently as of now.

**Comment by peterzhuamazon** [comment]
Not fully fixed. Still have issues.
