### ISSUE TITLE
Add tests for default .sh scripts and `scripts` directory

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#591]
### Is your feature request related to a problem? Please describe

Add tests for default scripts:

- [ ] `build.sh` 
- [ ] `bwctest.sh`
- [ ] `install.sh`
- [ ] `integtest.sh`
- [ ] `scripts/*`

**Comment by vchrombie** [comment]
Hi,

Is this issue still relevant?

I see some of the scripts deleted/moved.

I would like to pick this if it is available.

**Comment by gaiksaya** [comment]
Not sure what kind of tests are we expecting @saratvemulapalli . Do you mean check if the scripts exist or test the actually functionality? Considering they are shell scripts that call python entrypoints at the backend, seems like an overkill.
If this issue is not relevant, please feel free to close it.

Thanks!

**Comment by peterzhuamazon** [comment]
Updated with `scripts` directory as well.

**Comment by gaiksaya** [comment]
Closing this issue as stale.
