### ISSUE TITLE
Zenhub onboarding

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#616]
Our team is starting to use Zenhub for our work item tracking and there might be things that we need to figure out:

- [x] How should we track the 'oncall' time that is consumed by the team?
- [x] Add only tasks or create issues linked to the parent task?
- [x] Feels like we have to 'duplicate' a lot of work to create a new task or subtask - is there a way to add items with smarter defaults?
- [x] What should we look at during standup, is there a link we should always load?
- [x] How should we track work left during sprint planning 

Acceptance Criteria:
- [x] Create and have reviewed the process workflow document

**Comment by abhinavGupta16** [comment]
Following are a few ideas of how we should proceed with the process. We should discuss this more during one of the team meetings to get everyone's opinion and see what works best for us.

Explaining terminology of an Epic, it works like a meta issue _but with a lot more features_ reducing a lot of manual work and easy viewing. A brief list of advantages are below -
- It aggregates the story points of all the issues it houses and is easier to manage than github issues to go across sprints. I
- It would also help manage assignees etc automatically. 
- It provides a nice UI with a descrption of who worked on which issue, points for it, labels describing the issue and also progress bar showing completion of the work. 
- We can also have timelines separate from sprints attached to an Epic. 
- Epics can also be nested. 
- Click [here](https://help.zenhub.com/support/solutions/articles/43000010341-an-intro-to-zenhub-epics) for more more details.

An example of an Epic is below - 
- https://github.com/wishlists/wishlists/issues/74

--------

Listing out ideas for the questions - 

 - **How should we track the 'oncall' time that is consumed by the team?**
We could create an Epic or a meta issue for oncall, which would hold individual issues for every oncall person for the week. These sub issues could be used for any logging, work to be passed on.

- **Add only tasks or create issues linked to the parent task?**
Issues that span multiple sprints should be an Epic or a Meta issue. Such tasks should be broken into smaller tasks that can be accomplished during a sprint. All such tasks should be the part of the Epic/Meta issue

- **Feels like we have to 'duplicate' a lot of work to create a new task or subtask - is there a way to add items with smarter defaults?**
Creating a new task/story is same as creating a github issue. We should ideally not be working on any story/issue that is not present on github. We can create default templates for issues that can be optional (editable) to reduce work and provide structure. here is example I used in the past - https://github.com/wishlists/wishlists/tree/master/.github

- **What should we look at during standup, is there a link we should always load?**
We should look at the sprint board with added filter for the current sprint and the person who is providing updates. This would ensure that the work anyone is doing is in the right pipeline and a part of the board as well. Board should be visible as a part of the tab on github `opensearch-build` repo. This contains the issues for both `opensearch-build` and `opensearch-ci`. We should add any public repos here that we maybe working on. 

**Note:** We cannot add private repos since they require a paid membership.
