### ISSUE TITLE
[Requirements] IM needs JS 1.2.0 SPI in Maven Snapshots to work

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#663]
### Is your feature request related to a problem? Please describe

Per @dbbaughe,

```
We have changes going into job scheduler 1.2 and they are in the main branch, and we have a PR in index management that relies on those changes so it needs to be able to pull down the 1.2 snapshot if we bump them both to 1.2
```

We need to deploy 1.2 jars to maven as majority of the plugin owners are working on it in `main` branch of their repos.

### Describe the solution you'd like

Create 1.2.0 manifest and deploy to maven snapshots.

**Comment by dbbaughe** [comment]
As mentioned by Peter, we have already cut 1.1 branches for Job Scheduler and Index Management, and now we have a new feature going into the main branches of each w/ IM depending on the code changes in Job Scheduler. If we want to rely on using the snapshots for the dependencies in CI then we need to be able to bump the Job Scheduler/Index Management/other plugins to 1.2 and have the equivalent 1.2 SNAPSHOT jars/etc. created for the ones that publish something.

Otherwise we would have to revert back to checking out and building everything locally.

**Comment by dblock** [comment]
1. Make sure common-utils and job-scheduler have incremented their versions to 1.2.
2. Add them to the 1.2 manifest.
3. Start building 1.2 in https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/Jenkinsfile#L8.

**Comment by dblock** [comment]
@dbbaughe You should be able to PR all those changes, too!
