### ISSUE TITLE
[Bug] maven-metadata-local.xml files are preventing publishing to maven central

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#713]
When running stage-maven-release.sh all files from the build are included, there are some files such as `maven-metadata-local.xml` present that are causing problems when published because they have already been published.

We should determine if we can exclude these artifacts or if there are any additional artifacts that are not needed.

**Comment by dblock** [comment]
Let's find a way to test this without the metadata files, but I suspect we'll need them because the input to upload to Sonatype needs to be a working maven repo, which implies metadata files, but I could be wrong.

**Comment by mch2** [comment]
Metadata files are required when working with a maven repo.  The -local file is created because for some dependencies we were publishing to local and copying those files.  

With changes to push to a separate staging folder - https://github.com/opensearch-project/opensearch-plugins/pull/99/files, this file will be properly named.

**Comment by dblock** [comment]
Sounds like we can we close this then @mch2? Go for it.
