### ISSUE TITLE
Publish SQL CLI tool to pypi

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/opensearch-build#795]
The ODFE SQL CLI does not support compatibility in OpenSearch SQL, so we would like to publish the latest version of CLI to pypi to keep the SQL users up with the SQL changes.

**Comment by zhongnansu** [comment]
any update on this?

**Comment by zhongnansu** [comment]
@zelinh  I am the owner of sql-cli project and I can help with release it in Opensearch. The following is the old release process we follow in Opendistro.
 - github workflow to uploaded artifact to S3, as well as upload/release sql-cli on PyPI. Since previously we didn’t want to release sql-cli, so this workflow is commented out.
- The above workflow is set to be only triggered when a release tag “v*” is cut.
- the above workflow follows this release guide, provided by plugin team.

Do you think there will be any change for the release process? If not I’ll need
- the PyPI account credentials set up in repo

**Comment by zhongnansu** [comment]
We have issues in sql repo asking for sql-cli to be published to PyPI
https://github.com/opensearch-project/sql/issues/243
https://github.com/opensearch-project/sql/issues/374

**Comment by gaiksaya** [comment]
SQL CLI is published. Closing this issue.
