### ISSUE TITLE
[PROPOSAL] Release standalone plugins, such as mapper-murmur3

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-build#844]
## Actual
At the moment opensearch server plugin packages are published nowhere.

## Expected
Opensearch plugins should be published on [the website](https://opensearch.org/) and/or on the github repository. I mean to publish not just compiled `jar` file, but a `zip` acceptable by `opensearch-plugin` command line tool.

## Example 
When I needed to use `mapper-murmur3` plugin, I was surprised that it is not shipped OOTB. After some googling I found a compiled binary of the plugin on [maven](https://search.maven.org/artifact/org.opensearch.plugin/mapper-murmur3/1.1.0/jar) - it was a jar file, but the command line tool rejected it. No info which format of the input is required, no info how the `zip` package should looks like, no info what should be in the `plugin-descriptor.properties` file inside this zip. Fortunately, I succeeded to build it and to install the plugin, but it is an extremely user-unfriendly way.

Please, consider creating the proper CI workflow which will create these packages and publish them. Thank you.

**Comment by saratvemulapalli** [comment]
Looks like the question here is to publish plugin artifacts for community contributed plugins. 
Which definitely makes sense and we should do it.

The first step is to publish maven artifacts for plugins in opensearch-project.
Ref: https://github.com/opensearch-project/opensearch-build/issues/184

**Comment by peternied** [comment]
[Triage] @bbarani can you look into this proposal and see how this could fit into our release process and schedule?

**Comment by bbarani** [comment]
We have already released native plugins to artifacts.opensearch.org as part of every release starting 1.2.0. You should be able to install it directly using the plugin install command. You can also install the standalone plugin by passing the path of the Zip available within the manifest file of every distribution.

`./opensearch-plugin install https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.3/295/linux/x64/builds/opensearch/plugins/opensearch-alerting-1.2.3.0.zip`

You can refer to more details here - https://discuss.opendistrocommunity.dev/t/download-urls-for-plugins-not-listed-anywhere/8297/5?u=bbarani

We will work on uploading the zips to the artifacts.opensearch.org to support direct installation (without passing the URL) and you can track the status of that issue here #184
